name: build-freecad-pkgs

on:
  schedule:
    - cron: '30 23 * * *'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-freecad.yml'
      - PKGBUILD/freecad*
      - makepkg.conf
  workflow_dispatch:

concurrency:
  group: build-pkgs
  cancel-in-progress: true

jobs:
  build-pkg-upload:
    runs-on: ubuntu-latest
    container: ghcr.io/adrianinsaval/archbuilder:main
    env:
        SRCDEST: /home/build/src
        PKGDEST: /home/build/pkg
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Update packages
        run: pacman -Syu --noconfirm

      - name: Setup ccache
        uses: actions/cache@v3
        with:
          path: /home/build/.cache/ccache
          key: ccache

      - name: Setup sources cache
        uses: actions/cache@v3
        with:
          path: ${{ env.SRCDEST }}
          key: src-cache

      - name: Run makepkg
        run: |
          chown -R build:wheel .
          cp -p makepkg.conf /home/build/.makepkg.conf
          cd PKGBUILD/freecad-git
          su build --command='makepkg -s --noconfirm --nocheck'

      - name: Run namcap
        run: namcap -i $PKGDEST/*.pkg.*

      - name: Print ccache ussage statistics
        run: su build --command='ccache -s'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PKGDEST }}/*.pkg.*
          file_glob: true
          tag: archlinux
          overwrite: true
